version: '3.0'

services:
  postgres:
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_DB: "trail-trek"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5432:5432"
